"""Train CartPole-v1 with a small, educational GRPO-style algorithm.

This is the Gymnasium/current-PyTorch rewrite of the legacy ``code-1.py``.

Group Relative Policy Optimization (GRPO) replaces a learned value critic with
a group-relative baseline. For each training group, this example:

1. samples G complete trajectories from the same initial CartPole state;
2. calculates each trajectory's undiscounted episode return R_i;
3. standardizes returns inside the group,

       A_i = (R_i - mean(R_1, ..., R_G)) / (std(R_1, ..., R_G) + eps);

4. gives every action in trajectory i the scalar advantage A_i; and
5. reuses the group for several PPO-style clipped policy-update epochs.

This is a pedagogical adaptation of the central group-relative idea. Full LLM
GRPO implementations usually group multiple completions of one prompt, operate
on token sequences and reward models, and often include an explicit KL penalty
to a separate reference model. CartPole has no prompt or pretrained reference
model, so here a shared initial state acts as the common task and PPO clipping
constrains movement from the behavior (old) policy.
"""

import argparse
from dataclasses import dataclass
from pathlib import Path

import gymnasium as gym
import matplotlib.animation as animation
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.distributions import Categorical


@dataclass
class Trajectory:
    """One complete episode generated by the unchanged old policy."""

    states: list[np.ndarray]
    actions: list[int]
    old_log_probabilities: list[float]
    episode_return: float


@dataclass
class UpdateStatistics:
    """Diagnostics summarized across the repeated GRPO update epochs."""

    loss: float
    approximate_kl: float
    clip_fraction: float
    completed_epochs: int


class PolicyNet(nn.Module):
    """Represent the stochastic categorical policy pi_theta(a | s)."""

    def __init__(self, state_size: int, action_size: int):
        super().__init__()
        self.hidden = nn.Linear(state_size, 128)
        self.output = nn.Linear(128, action_size)

    def forward(self, states: torch.Tensor) -> torch.Tensor:
        hidden = F.relu(self.hidden(states))
        # Return logits rather than softmax probabilities. Categorical can
        # compute stable probabilities and log probabilities directly.
        return self.output(hidden)


class GRPOAgent:
    """Optimize one policy from group-standardized trajectory returns."""

    def __init__(
        self,
        state_size: int,
        action_size: int,
        clip_epsilon: float,
        update_epochs: int,
        target_kl: float,
    ):
        self.clip_epsilon = clip_epsilon
        self.update_epochs = update_epochs
        self.target_kl = target_kl
        self.entropy_coefficient = 0.001

        # Unlike Actor-Critic, GAE, and PPO examples from Day 3, this agent has
        # no ValueNet and no critic optimizer. The group mean is its baseline.
        self.policy = PolicyNet(state_size, action_size)
        self.optimizer = optim.Adam(self.policy.parameters(), lr=0.0003)

    def choose_action(
        self,
        state: np.ndarray,
        *,
        greedy: bool = False,
    ) -> tuple[int, float]:
        """Sample during training and optionally act greedily for evaluation."""
        state_tensor = torch.as_tensor(state, dtype=torch.float32)
        with torch.no_grad():
            distribution = Categorical(logits=self.policy(state_tensor))

            if greedy:
                action_tensor = torch.argmax(distribution.logits)
            else:
                action_tensor = distribution.sample()

            old_log_probability = distribution.log_prob(action_tensor)

        return int(action_tensor.item()), float(old_log_probability.item())

    def collect_trajectory(
        self,
        env: gym.Env,
        seed: int,
    ) -> Trajectory:
        """Collect one episode without retaining an autograd graph.

        ``seed`` is shared by every trajectory in the current group, so each
        starts from the same CartPole state. Their returns differ because the
        stochastic policy samples different action sequences. This mirrors the
        GRPO idea of comparing several outputs for one common task or prompt.

        Network weights do not change here. Therefore all saved log
        probabilities describe one fixed behavior policy pi_old.
        """
        state, _ = env.reset(seed=seed)
        states: list[np.ndarray] = []
        actions: list[int] = []
        old_log_probabilities: list[float] = []
        episode_return = 0.0

        terminated = truncated = False
        while not (terminated or truncated):
            action, old_log_probability = self.choose_action(state)
            next_state, reward, terminated, truncated, _ = env.step(action)

            states.append(state)
            actions.append(action)
            old_log_probabilities.append(old_log_probability)
            episode_return += float(reward)
            state = next_state

        return Trajectory(
            states=states,
            actions=actions,
            old_log_probabilities=old_log_probabilities,
            episode_return=episode_return,
        )

    def collect_group(
        self,
        env: gym.Env,
        group_size: int,
        group_seed: int,
    ) -> list[Trajectory]:
        """Sample G independent trajectories from one unchanged policy."""
        # Reusing group_seed intentionally reproduces the same initial state.
        # PyTorch's action-sampling RNG is not reset, so action sequences remain
        # different across trajectories.
        return [
            self.collect_trajectory(env, seed=group_seed)
            for _ in range(group_size)
        ]

    @staticmethod
    def calculate_group_advantages(
        trajectories: list[Trajectory],
    ) -> torch.Tensor:
        """Standardize complete-trajectory returns within the current group.

        There is one advantage per trajectory, not one TD/GAE advantage per
        transition. If every return is equal, every relative advantage is zero
        and the group provides no preference-learning signal.
        """
        returns = torch.tensor(
            [trajectory.episode_return for trajectory in trajectories],
            dtype=torch.float32,
        )
        mean_return = returns.mean()
        standard_deviation = returns.std(unbiased=False)

        return (returns - mean_return) / (standard_deviation + 1e-8)

    def prepare_group_batch(
        self,
        trajectories: list[Trajectory],
        group_advantages: torch.Tensor,
    ) -> tuple[
        torch.Tensor,
        torch.Tensor,
        torch.Tensor,
        torch.Tensor,
        torch.Tensor,
    ]:
        """Flatten variable-length trajectories while preserving equal weight.

        The legacy code first averaged losses across time within each trajectory
        and then averaged across trajectories. A long trajectory and a short
        trajectory therefore had equal overall group weight. The flattened
        implementation reproduces that behavior with per-transition weights:

            weight_(i,t) = 1 / length(trajectory_i).

        The final loss divides the weighted sum by the group size.
        """
        state_batches: list[torch.Tensor] = []
        action_batches: list[torch.Tensor] = []
        old_log_probability_batches: list[torch.Tensor] = []
        advantage_batches: list[torch.Tensor] = []
        trajectory_weight_batches: list[torch.Tensor] = []

        for trajectory, advantage in zip(
            trajectories,
            group_advantages,
            strict=True,
        ):
            trajectory_length = len(trajectory.states)
            state_batches.append(
                torch.as_tensor(
                    np.asarray(trajectory.states),
                    dtype=torch.float32,
                )
            )
            action_batches.append(
                torch.tensor(trajectory.actions, dtype=torch.int64)
            )
            old_log_probability_batches.append(
                torch.tensor(
                    trajectory.old_log_probabilities,
                    dtype=torch.float32,
                )
            )

            # Repeat the same outcome-level group advantage at every action in
            # the corresponding trajectory.
            advantage_batches.append(
                advantage.repeat(trajectory_length)
            )
            trajectory_weight_batches.append(
                torch.full(
                    (trajectory_length,),
                    1.0 / trajectory_length,
                    dtype=torch.float32,
                )
            )

        return (
            torch.cat(state_batches),
            torch.cat(action_batches),
            torch.cat(old_log_probability_batches),
            torch.cat(advantage_batches),
            torch.cat(trajectory_weight_batches),
        )

    def update(self, trajectories: list[Trajectory]) -> UpdateStatistics:
        """Reuse one group with GRPO's clipped policy objective.

        The old policy log probabilities and relative advantages remain fixed
        throughout this call. The current policy changes after every optimizer
        step, producing a new probability ratio on the next epoch.
        """
        group_advantages = self.calculate_group_advantages(trajectories)
        (
            states,
            actions,
            old_log_probabilities,
            repeated_advantages,
            trajectory_weights,
        ) = self.prepare_group_batch(trajectories, group_advantages)

        group_size = len(trajectories)
        losses: list[float] = []
        approximate_kls: list[float] = []
        clip_fractions: list[float] = []
        completed_epochs = 0

        for _ in range(self.update_epochs):
            distribution = Categorical(logits=self.policy(states))
            new_log_probabilities = distribution.log_prob(actions)

            # r_(i,t)(theta) = pi_theta(A_(i,t)|S_(i,t))
            #                    / pi_old(A_(i,t)|S_(i,t))
            log_ratios = new_log_probabilities - old_log_probabilities
            probability_ratios = torch.exp(log_ratios)
            clipped_ratios = torch.clamp(
                probability_ratios,
                1.0 - self.clip_epsilon,
                1.0 + self.clip_epsilon,
            )

            # Every transition from trajectory i uses its scalar group-relative
            # advantage A_i. The minimum is PPO/GRPO's conservative clipped
            # surrogate objective.
            unclipped_surrogate = (
                probability_ratios * repeated_advantages
            )
            clipped_surrogate = clipped_ratios * repeated_advantages
            conservative_surrogate = torch.minimum(
                unclipped_surrogate,
                clipped_surrogate,
            )

            # Weighted summation exactly means:
            #
            #   -(1/G) * sum_i (1/T_i) * sum_t surrogate_(i,t).
            #
            # Thus each trajectory receives equal weight even though successful
            # CartPole trajectories are usually longer.
            policy_loss = -(
                conservative_surrogate * trajectory_weights
            ).sum() / group_size

            weighted_entropy = (
                distribution.entropy() * trajectory_weights
            ).sum() / group_size
            loss = policy_loss - self.entropy_coefficient * weighted_entropy

            self.optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(
                self.policy.parameters(),
                max_norm=0.5,
            )
            self.optimizer.step()

            # These diagnostics measure movement away from pi_old. They do not
            # contribute gradients to the policy loss.
            with torch.no_grad():
                per_transition_kl = (
                    (probability_ratios - 1.0) - log_ratios
                )
                approximate_kl = (
                    per_transition_kl * trajectory_weights
                ).sum() / group_size
                # Exact arithmetic is nonnegative; remove tiny negative values
                # such as -0.00000 caused by floating-point roundoff.
                approximate_kl = approximate_kl.clamp_min(0.0)

                was_clipped = (
                    (probability_ratios - 1.0).abs()
                    > self.clip_epsilon
                ).float()
                clip_fraction = (
                    was_clipped * trajectory_weights
                ).sum() / group_size

            losses.append(float(loss.item()))
            approximate_kls.append(float(approximate_kl.item()))
            clip_fractions.append(float(clip_fraction.item()))
            completed_epochs += 1

            # Clipping is a soft constraint. Approximate-KL early stopping is
            # an additional safeguard against an unusually large update.
            if approximate_kl.item() > self.target_kl:
                break

        return UpdateStatistics(
            loss=float(np.mean(losses)),
            approximate_kl=float(np.mean(approximate_kls)),
            clip_fraction=float(np.mean(clip_fractions)),
            completed_epochs=completed_epochs,
        )


def train(
    agent: GRPOAgent,
    env: gym.Env,
    max_groups: int,
    group_size: int,
    seed: int,
    solved_window: int,
    target_return: float,
) -> tuple[list[list[float]], bool]:
    """Alternate between fresh group collection and one GRPO update."""
    group_returns_history: list[list[float]] = []

    for group_number in range(1, max_groups + 1):
        # COLLECTION PHASE: sample a new comparison group with pi_old.
        trajectories = agent.collect_group(
            env,
            group_size=group_size,
            group_seed=seed + group_number - 1,
        )
        group_returns = [
            trajectory.episode_return for trajectory in trajectories
        ]

        # UPDATE PHASE: reuse only this group for several clipped epochs.
        statistics = agent.update(trajectories)
        group_returns_history.append(group_returns)

        recent_groups = group_returns_history[-solved_window:]
        recent_mean = float(np.mean(recent_groups))

        if group_number == 1 or group_number % 10 == 0:
            print(
                f"Group {group_number:4d} | "
                f"return {np.mean(group_returns):6.1f} "
                f"+/- {np.std(group_returns):5.1f} | "
                f"recent {recent_mean:6.1f} | "
                f"loss {statistics.loss:8.4f} | "
                f"KL {statistics.approximate_kl:7.5f} | "
                f"clip {statistics.clip_fraction:5.1%} | "
                f"epochs {statistics.completed_epochs:2d}"
            )

        if (
            len(group_returns_history) >= solved_window
            and recent_mean >= target_return
        ):
            print(
                f"Solved after {group_number} groups: "
                f"recent mean return {recent_mean:.1f}."
            )
            return group_returns_history, True

    final_window = group_returns_history[-solved_window:]
    print(
        f"Stopped after {max_groups} groups; recent mean return "
        f"{np.mean(final_window):.1f}."
    )
    return group_returns_history, False


def evaluate(
    agent: GRPOAgent,
    episodes: int,
    seed: int,
) -> list[float]:
    """Evaluate the deterministic greedy policy without changing weights."""
    env = gym.make("CartPole-v1")
    returns: list[float] = []

    try:
        for episode in range(episodes):
            state, _ = env.reset(seed=seed + episode)
            terminated = truncated = False
            episode_return = 0.0

            while not (terminated or truncated):
                action, _ = agent.choose_action(state, greedy=True)
                state, reward, terminated, truncated, _ = env.step(action)
                episode_return += float(reward)

            returns.append(episode_return)
    finally:
        env.close()

    print(
        f"Greedy evaluation over {episodes} episodes: "
        f"{np.mean(returns):.1f} +/- {np.std(returns):.1f}"
    )
    return returns


def save_greedy_animation(
    agent: GRPOAgent,
    seed: int,
    output_path: Path,
) -> None:
    """Render one greedy episode and save it as a GIF."""
    env = gym.make("CartPole-v1", render_mode="rgb_array")
    frames: list[np.ndarray] = []

    try:
        state, _ = env.reset(seed=seed)
        terminated = truncated = False

        while not (terminated or truncated):
            frame = env.render()
            if frame is not None:
                frames.append(frame)

            action, _ = agent.choose_action(state, greedy=True)
            state, _, terminated, truncated, _ = env.step(action)
    finally:
        env.close()

    if not frames:
        raise RuntimeError("Gymnasium returned no RGB frames")

    figure, axis = plt.subplots(figsize=(6, 4))
    axis.axis("off")
    artists = [
        [axis.imshow(frame, animated=True)] for frame in frames
    ]
    result = animation.ArtistAnimation(
        figure,
        artists,
        interval=40,
        blit=True,
    )
    result.save(output_path, writer="pillow")
    plt.close(figure)
    print(f"Saved greedy animation to: {output_path}")


def plot_training(
    group_returns_history: list[list[float]],
    output_path: Path,
) -> None:
    """Plot group means and the within-group return range."""
    group_numbers = np.arange(1, len(group_returns_history) + 1)
    group_array = np.asarray(group_returns_history, dtype=np.float32)
    group_means = group_array.mean(axis=1)
    group_minima = group_array.min(axis=1)
    group_maxima = group_array.max(axis=1)

    figure, axis = plt.subplots(figsize=(9, 5))
    axis.fill_between(
        group_numbers,
        group_minima,
        group_maxima,
        alpha=0.15,
        label="Within-group range",
    )
    axis.plot(group_numbers, group_means, alpha=0.35, label="Group mean")

    window_size = min(20, len(group_means))
    if window_size > 1:
        moving_average = np.convolve(
            group_means,
            np.ones(window_size) / window_size,
            mode="valid",
        )
        axis.plot(
            group_numbers[window_size - 1 :],
            moving_average,
            label=f"{window_size}-group moving average",
        )

    axis.set(
        xlabel="Training group",
        ylabel="Episode return",
        title="GRPO-style training on CartPole-v1",
    )
    axis.legend()
    figure.tight_layout()
    figure.savefig(output_path, bbox_inches="tight")
    plt.close(figure)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train a GRPO-style policy on CartPole-v1."
    )
    parser.add_argument("--max-groups", type=int, default=500)
    parser.add_argument("--group-size", type=int, default=8)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--clip-epsilon", type=float, default=0.2)
    parser.add_argument("--update-epochs", type=int, default=10)
    parser.add_argument("--target-kl", type=float, default=0.02)
    parser.add_argument("--solved-window", type=int, default=20)
    parser.add_argument("--target-return", type=float, default=475.0)
    parser.add_argument("--evaluation-episodes", type=int, default=10)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).with_name("grpo-training.pdf"),
        help="Path of the training plot.",
    )
    parser.add_argument(
        "--animation-output",
        type=Path,
        default=None,
        help="Optional path for a greedy-evaluation GIF.",
    )
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    """Reject values that make the group comparison or update invalid."""
    if args.max_groups < 1:
        raise ValueError("--max-groups must be at least 1")
    if args.group_size < 2:
        raise ValueError("--group-size must be at least 2")
    if not 0.0 < args.clip_epsilon < 1.0:
        raise ValueError("--clip-epsilon must be between 0 and 1")
    if args.update_epochs < 1:
        raise ValueError("--update-epochs must be at least 1")
    if args.target_kl <= 0.0:
        raise ValueError("--target-kl must be positive")
    if args.solved_window < 1:
        raise ValueError("--solved-window must be at least 1")
    if args.evaluation_episodes < 1:
        raise ValueError("--evaluation-episodes must be at least 1")


def main() -> None:
    args = parse_args()
    validate_args(args)

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    env = gym.make("CartPole-v1")
    env.action_space.seed(args.seed)
    state_size = int(env.observation_space.shape[0])
    action_size = int(env.action_space.n)
    agent = GRPOAgent(
        state_size,
        action_size,
        clip_epsilon=args.clip_epsilon,
        update_epochs=args.update_epochs,
        target_kl=args.target_kl,
    )

    try:
        group_returns_history, _ = train(
            agent,
            env,
            max_groups=args.max_groups,
            group_size=args.group_size,
            seed=args.seed,
            solved_window=args.solved_window,
            target_return=args.target_return,
        )
    finally:
        env.close()

    plot_training(group_returns_history, args.output)
    print(f"Saved training plot to: {args.output}")

    evaluate(
        agent,
        episodes=args.evaluation_episodes,
        seed=args.seed + 100_000,
    )

    if args.animation_output is not None:
        save_greedy_animation(
            agent,
            seed=args.seed + 200_000,
            output_path=args.animation_output,
        )


if __name__ == "__main__":
    main()

#   uv run python rl_learning_demo/day04/code-1-grpo.py